<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "iwda_word2digi"
 *
 * Auto generated by Extension Builder 2017-10-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Word2Digi',
    'description' => 'Automatischer Upload von docx zu Typo3',
    'category' => 'module',
    'author' => 'David Iwertowski',
    'author_email' => '',
    'state' => 'beta',
    'internal' => '',
    'dependencies' => 'extbase',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.9.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            'php' => '5.3.0',
            'restler' => '1.5.0-0.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
